### PR TITLE
adding notification to system proxy, resolving #474

### PR DESCRIPTION
**Pull request by DuckSoft**

### CODE REVIEW

**Comment by DuckSoft** [comment]
Ready for Review.

**Comment by Qv2ray-dev** [comment]
LGTM

**Comment by Qv2ray-dev** [comment]
We may need to unify the API call, there are `ClearSystemProxy` and `MWClearSystemProxy` mixing in the code.

**Comment by DuckSoft** [comment]
@Qv2ray-dev You

**Comment by Qv2ray-dev** [comment]
Anyway just merge it and thanks.

**Pull request merged**
