### PR TITLE
Use zxing-cpp

### PR DESCRIPTION
**Pull request by Qv2ray-dev**

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
[**Blocking**]
@DuckSoft @zzndb @axionl 

This is a breaking change, more details will be provided soon by @ymshenyu

**Comment by Qv2ray-dev** [comment]
Removed WIP prefix.

**Comment by DuckSoft** [comment]
@Qv2ray-dev hold on

**Comment by Qv2ray-dev** [comment]
Can this be merged?

**Comment by DuckSoft** [comment]
Change Confirmation
- [ ] @DuckSoft 
- [ ] @ymshenyu 
- [ ] @zzndb

**Comment by DuckSoft** [comment]
All changes acknowledged.
@Qv2ray-dev awaiting further actions

**Comment by Qv2ray-dev** [comment]
Merging

**Pull request merged**
