### PR TITLE
add qt6 support for QRE

### PR DESCRIPTION
**Pull request by Mon-ius**
Try to fix the compile error on mac side with qt6 (Qwidget)

### CODE REVIEW

**Comment by dyhkwong** [comment]
把 Qt5 的 QRegExp 也换成 QRegularExpression 吧

**Comment by Mon-ius** [comment]
merge it first, I need to test it.

**Comment by dyhkwong** [comment]
> merge it first, I need to test it.

You can enable Actions in your fork to test it.
The `QRegularExpression` part of code looks okay on Qt >= 5.12. For Qt 5.11 (Qv2ray minimal support version, no anchoredPattern), you may need `const static QRegularExpression sha256("^[0-9a-fA-F]{64}$")` or something else.

**Comment by Mon-ius** [comment]
You can keep the current fix for the 2.7 version. In this commit, I still keep the support for  Qt 5.11 version. Once you have the idea to move on to the next version, such as 2.8 or 3.0+, then that is a good chance to remove all old feature such as QRegExp, and thus increase the minimum supported version, such as 5.12. I have tested it could work and build success on my side, for both QML and QWidget UI type on macOS. Here to ask for the merge, one for share the solution for macOS build(have not it ever build success on your action for macOS with Qt6 since I follow the repo), another to see if it works well for other platform users.

**Comment by dyhkwong** [comment]
@Mon-ius This will cause some build failure. I have fixed build on old versions of Qt but I don't have permission to push to your branch. Please apply this patch 9658939 and it will get merged.

**Comment by Mon-ius** [comment]
Thanks for the test for the old version of Qt. I have now applied the patch.

**Review by dyhkwong — APPROVED** [review]

**Pull request merged**
