### PR TITLE
feat: add zh_TW translation

### PR DESCRIPTION
**Pull request by nczitzk**

### CODE REVIEW

**Comment by U-v-U** [comment]
Please edit the `cmake/translations.cmake` as well.

**Comment by DuckSoft** [comment]
@U-v-U maybe later we need to cherry pick this commit to dev branch and do a sync.

**Comment by nczitzk** [comment]
> Please edit the `cmake/translations.cmake` as well.

Sorry...I am not sure what I should modify in `cmake/translations.cmake` 😭. A hint would be nice.

**Comment by DuckSoft** [comment]
> > Please edit the `cmake/translations.cmake` as well.
> 
> Sorry...I am not sure what I should modify in `cmake/translations.cmake` sob. A hint would be nice.

Never mind. Nothing to modify.

**Comment by DuckSoft** [comment]
Tested and is working perfectly. Merging!

ps: next time please use `dev` as base branch~

**Comment by nczitzk** [comment]
> Tested and is working perfectly. Merging!
> 
> ps: next time please use `dev` as base branch~

Thanks for reviewing and merging. Will do 👌.

**Pull request merged**
