### PR TITLE
feat: grpc mode

### PR DESCRIPTION
**Pull request by Sinofine**

### CODE REVIEW

**Comment by Sinofine** [comment]
oops I've confused share url spec with JSON structs' actual struction.
sorry I'll correct that.

**Comment by Sinofine** [comment]
As for `guna`, it seems that it's not implemented according to xray docs, so I leave the selection default as `gun` despite selecting `guna`.
When selecting mode `multi`,`grpcSettings.multiMode` in JSON struct is set `true`, and the default choice `gun` makes it unset.
that's my point of view.

**Comment by DuckSoft** [comment]
@Sinofine correct. that is it.

**Comment by DuckSoft** [comment]
but... in your code, it seemed multiMode is not a boolean...

**Pull request closed without merging**
