### PR TITLE
[WIP] Port to CMake build system instead of QMake

### PR DESCRIPTION
**Pull request by Qv2ray-dev**

### CODE REVIEW

**Comment by DuckSoft** [comment]
We are ready to go.
(except that snap)

**Comment by DuckSoft** [comment]
Quick Review:
* Windows:
   - [ ] bug: console window is shown
   - [ ] bug: no icon in exe file
* macOS:
   - [ ] bang

**Comment by Qv2ray-dev** [comment]
macOS app bundle test passed.

**Comment by Qv2ray-dev** [comment]
Known bugs in this build:
- PAC HTTP Server will block up the whole application
- Automatic migration from old `v2CorePath` and `v2AssetsPath` is buggy currently.
- Some UI elements are not having dark mode icons.

**Comment by Qv2ray-dev** [comment]
Now ready to review

**Comment by DuckSoft** [comment]
图片
Still having problem in AppImage. Check that pipeline?

**Comment by Qv2ray-dev** [comment]
> Known bugs in this build:
> 
>     * PAC HTTP Server will block up the whole application
> 
>     * Automatic migration from old `v2CorePath` and `v2AssetsPath` is buggy currently.
> 
>     * Some UI elements are not having dark mode icons.

- Translations are not detected when using AppImage, (and possibly macOS .app)

**Pull request merged**
