### PR TITLE
Qv2ray v2.2 alpha 1 draft

### PR DESCRIPTION
**Pull request by Qv2ray-dev**
This is still WIP.

No new feature in this release but only the UI updates.

### CODE REVIEW

**Comment by DuckSoft** [comment]
Great. Seems that we will soon have a nice and clean interface.

**Comment by Qv2ray-dev** [comment]
This PR is currently ready for review.
cc @DuckSoft @axionl

**Comment by DuckSoft** [comment]
Review In Progress

**Comment by Qv2ray-dev** [comment]
This PR is currently blocked by a mysterious issue.

**Pull request merged**
