### PR TITLE
fix: Replace currentIndexChanged(const QString&) with currentTextChan…

### PR DESCRIPTION
**Pull request by hzdrro**
…QString&)

According to the documentation[1], it seems that there is no signal defined as "currentIndexChanged(const QString&)" but "currentTextChanged(const QString&)" for QComboBox, which makes some streamsettings unchangeable.

1. https://doc.qt.io/qt-6/qcombobox.html#signals

### CODE REVIEW

**Comment by hzdrro** [comment]
And there are several more currentIndexChanged(const QString&) in other files, I'm not sure if I should replace them all.

**Comment by U-v-U** [comment]
Thanks for your PR!

According to Qt source code. 
```
Use currentIndexChanged(int) instead, and get the text using itemText(index)
```

It could be better to follow the upstream suggestions.

**Comment by hzdrro** [comment]
@U-v-U I made the changes.

**Review by U-v-U — APPROVED** [review]

**Comment by U-v-U** [comment]
Thanks!

**Pull request merged**
