### PR TITLE
fix StackTrace features.

### PR DESCRIPTION
**Pull request by Qv2ray-dev**
```
!!    DO  NOT  MERGE     !!
!! A BOMB IS IN THE CODE !!
```

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
```
!!    REVIEWS REQUIRED     !!
!!  BOMB HAS BEEN REMOVED  !!
```

**Comment by Qv2ray-dev** [comment]
```
DO NOT MERGE!

Qv2ray/build dev-test-stacktrace > sudo cmake --install .                                                                                1m28s[6d50d26]
-- Install configuration: ""
-- Installing: /usr/local/bin/qv2ray
-- Up-to-date: /usr/local/share/metainfo/qv2ray.metainfo.xml
-- Up-to-date: /usr/local/share/applications/qv2ray.desktop
-- Up-to-date: /usr/local/share/icons/hicolor/256x256/apps/qv2ray.png
-- Up-to-date: /usr/local/share/qv2ray/lang/en_US.qm
-- Up-to-date: /usr/local/share/qv2ray/lang/ja_JP.qm
-- Up-to-date: /usr/local/share/qv2ray/lang/ru_RU.qm
-- Up-to-date: /usr/local/share/qv2ray/lang/zh_CN.qm
-- Installing: /usr/local/include/backward.hpp
-- Installing: /usr/local/lib/backward/BackwardConfig.cmake
```

**Comment by DuckSoft** [comment]
That was way too dirty...

> ```
> DO NOT MERGE!
> 
> Qv2ray/build dev-test-stacktrace > sudo cmake --install .                                                                                1m28s[6d50d26]
> -- Install configuration: ""
> -- Installing: /usr/local/bin/qv2ray
> -- Up-to-date: /usr/local/share/metainfo/qv2ray.metainfo.xml
> -- Up-to-date: /usr/local/share/applications/qv2ray.desktop
> -- Up-to-date: /usr/local/share/icons/hicolor/256x256/apps/qv2ray.png
> -- Up-to-date: /usr/local/share/qv2ray/lang/en_US.qm
> -- Up-to-date: /usr/local/share/qv2ray/lang/ja_JP.qm
> -- Up-to-date: /usr/local/share/qv2ray/lang/ru_RU.qm
> -- Up-to-date: /usr/local/share/qv2ray/lang/zh_CN.qm
> -- Installing: /usr/local/include/backward.hpp
> -- Installing: /usr/local/lib/backward/BackwardConfig.cmake
> ```

**Comment by Qv2ray-dev** [comment]
Unwanted install targets has been fixed in [`5a12beb` (#714)](https://github.com/Qv2ray/Qv2ray/pull/714/commits/5a12beb59af69f7b1197571e80e6ad3c4b2ab710)

**Comment by DuckSoft** [comment]
@Qv2ray-dev Good Job!

**Comment by Qv2ray-dev** [comment]
@DuckSoft Please review.

**Pull request merged**
