### PR TITLE
Feat: Option to override mux

### PR DESCRIPTION
**Pull request by hzdrro**

### CODE REVIEW

**Comment by dyhkwong** [comment]
Is it intended to override mux only for VMess and VLESS? Should notice users about that.
PS. seems that enabling mux for VLESS will make many of its mechanisms invalid. I think VLESS is not designed for using together with mux.

**Comment by hzdrro** [comment]
> 
> 
> Is it intended to override mux only for VMess and VLESS? Should notice users about that.
> PS. seems that enabling mux for VLESS will make many of its mechanisms invalid. I think VLESS is not designed for using together with mux.

Maybe some checkboxs could be added to choose what protocols are to be overrided?

**Comment by U-v-U** [comment]
Why not add it to `GroupRoutingConfig` in `QvConfigIdentifier.hpp` in case someone would set it in for a specific group?

**Comment by hzdrro** [comment]
> 
> 
> Why not add it to `GroupRoutingConfig` in `QvConfigIdentifier.hpp` in case someone would set it in for a specific group?
> 
>     * For a global scoped configuration there's a `defaultRouteConfig` in `GlobalConfig` avaliable.
> 
> 
> `Qv2rayConfig_Advanced` was used for options considered as advanced and dangerous.

`GroupRoutingConfig` is beyond by reach. So I moved the configuration to `GroupRoutingConfig.connectionConfig` and added checkboxs for specific protocols.

**Comment by U-v-U** [comment]
We are currently working on moving "global" options to "per-group" option, that would be better for our future migration.

**Comment by DuckSoft** [comment]
hmmmm, why closed this? i thought it was great.

**Comment by hzdrro** [comment]
> 
> 
> hmmmm, why closed this? i thought it was great.

"per-group" option which is preferred seems to be far too complicated for me.

**Pull request closed without merging**
