### PR TITLE
Port Detector Implementation

### PR DESCRIPTION
**Pull request by DuckSoft**
Tracker: #595

### CODE REVIEW

**Comment by DuckSoft** [comment]
@Qv2ray-dev please review. if it's possible to use this feature, you can change the merge base from `dev` into your current working branch.

**Comment by Qv2ray-dev** [comment]
@DuckSoft ack

**Comment by Qv2ray-dev** [comment]
Was this feature tested?

**Comment by DuckSoft** [comment]
> Was this feature tested?

Not tested, but should at least work though.

**Comment by Qv2ray-dev** [comment]
Since there's no caller *yet*... It could be merged.

**Pull request merged**
