### PR TITLE
make vmess link parsing more robust

### PR DESCRIPTION
**Pull request by tleydxdy**
also took care of some dead code

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
@tleydxdy thanks

**Comment by Qv2ray-dev** [comment]
There are a lot of changes.
So we need some time investigating.

cc @DuckSoft

**Comment by DuckSoft** [comment]
LGTM. Let's merge to dev and have a check.

**Comment by Qv2ray-dev** [comment]
Thanks for your contribution @tleydxdy

**Pull request merged**
