### PR TITLE
Added logger mutex.

### PR DESCRIPTION
**Pull request by Qv2ray-dev**
Just to review if anything should be done before merging.

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
@DuckSoft Please review, this will be in Qv2ray 2.1

**Comment by DuckSoft** [comment]
mutex applies upon insertion, but is missing during deletion and peeking.

**Comment by Qv2ray-dev** [comment]
Resolved, this should not break our CI.

**Comment by DuckSoft** [comment]
Performance issues may occur. A benchmark is suggested before letting go. 
I will compile and run on my machine now.

**Comment by Qv2ray-dev** [comment]
Since our log doesn't occur too (compared to the V2ray Core one) frequently, this shouldn't be a serious problem.

There's no report of corrupted log content before as well.

**Comment by DuckSoft** [comment]
Refactored with a more wise strategy.

**Pull request merged**
