### PR TITLE
CMakeLists: update default paths on macos

### PR DESCRIPTION
**Pull request by holymonson**
macos 上 homebrew 的 v2ray 位于 `/usr/local/opt/v2ray`，更改为默认路径。

### CODE REVIEW

**Comment by U-v-U** [comment]
Default paths should not be specified within the CMakeLists
Please modify the CI configuration instead.

Thanks

**Comment by DuckSoft** [comment]
What? Are you sure? Please show us how you install `v2ray` through Homebrew, will you?

**Comment by kidonng** [comment]
What Homebrew tap did you install V2Ray from? AFAIK homebrew/core and v2ray/v2ray-core are all using /usr/local/bin/v2ray.

**Comment by holymonson** [comment]
@DuckSoft @kidonng 
I installed `v2ray` from `homebrew/core` and `Qv2ray` from `homebrew/cask`. And the `Qv2ray` from `homebrew/cask` depends on `v2ray` now (via https://github.com/Homebrew/homebrew-cask/pull/93882). This patch could make `Qv2ray` (`Qv2ray.VERSION.macOS-x64.dmg`) out-of-the-box, no need for new users to config `v2ray` paths on macOS.

Those paths are correct on macOS with homebrew. 
```
❯ ll /usr/local/bin/v2ray
lrwxr-xr-x 1 monson admin 32 11 30 14:53 /usr/local/bin/v2ray -> ../Cellar/v2ray/4.33.0/bin/v2ray
❯ ll /usr/local/opt/v2ray
lrwxr-xr-x 1 monson admin 22 11 30 14:53 /usr/local/opt/v2ray -> ../Cellar/v2ray/4.33.0
❯ ll /usr/local/opt/v2ray/bin
total 31M
-r-xr-xr-x 1 monson staff 13M 11 20 16:09 v2ctl
-r-xr-xr-x 1 monson staff 19M 11 20 16:09 v2ray
❯ ll /usr/local/opt/v2ray/share/v2ray
total 5.9M
-rw-r--r-- 1 monson staff 5.0M 11 20 16:09 geoip.dat
-rw-r--r-- 1 monson staff 922K 11 20 16:09 geosite.dat
```

I'm not familiar with your CI configuration, perhaps you could modify it. The default paths won't bother me again, they only bother new users. Thanks.

**Review by DuckSoft — APPROVED** [review]
Fine.

**Comment by DuckSoft** [comment]
@U-v-U please review now

**Comment by U-v-U** [comment]
Done in https://github.com/Qv2ray/Qv2ray/commit/07fc8ce594cde49113107dfb0a2b8061be1548f3

**Pull request closed without merging**
