### PR TITLE
add dns intercept and route for tproxy 

### PR DESCRIPTION
**Pull request by springzfx**
socks and http proxy can use v2ray inner dns resolver, while tproxy can not.
Intercept and route dns request to  dns outbund, then inner dns resolver handle this.
With this and doh, dns posion can be avoid.

### CODE REVIEW

**Comment by springzfx** [comment]
This feature only useful for tproxy.
image

**Comment by Qv2ray-dev** [comment]
LGTM

**Comment by huyizheng** [comment]
2 problems perhaps:
1. The outbound "dns-out" should also set so-mark if possible, otherwise, the dns-out traffic may have infinity loop.
2. The rule to dns-out should add "network:udp", otherwise, tcp traffic to port 53 will also be hijacked to dns-out.

**Comment by huyizheng** [comment]
> 2 problems perhaps:
> 
>     1. The outbound "dns-out" should also set so-mark if possible, otherwise, the dns-out traffic may have infinity loop.
> 
>     2. The rule to dns-out should add "network:udp", otherwise, tcp traffic to port 53 will also be hijacked to dns-out.

[0001-Fix-dns-tproxy-issue.txt](https://github.com/Qv2ray/Qv2ray/files/4526227/0001-Fix-dns-tproxy-issue.txt)
I created a simple patch to fix these 2 issues.

**Comment by springzfx** [comment]
So why tcp dns should not be hijacked, any special? 
I think dns intercepet should handle all dns request.

**Comment by huyizheng** [comment]
> So why tcp dns should not be hijacked, any special?
> I think dns intercepet should handle all dns request.

My mistake.
I forgot that dns also has tcp 53 port.

So just the first problem is actually a problem. and to fix it just swap dns outbound settings and mark settings like the patch.

**Comment by springzfx** [comment]
OK, I will handle first problem, good idea.

**Pull request merged**
