### PR TITLE
Fix compatibility between v2ray 5.x and Qv2ray

### PR DESCRIPTION
**Pull request by Integral-Tech**
Fix a compatibility issue between v2ray 5.x and Qv2ray.

### CODE REVIEW

**Comment by moodyhunter** [comment]
@Integral-Tech There has been a branch working on this https://github.com/Qv2ray/Qv2ray/tree/v5

**Comment by xz-dev** [comment]
PR is not available, my patch for src/core/kernel/V2RayKernelInteractions.cpp

``` diff
--- src/core/kernel/V2RayKernelInteractions.cpp	2022-09-21 23:59:49.625166571 +0800
+++ /home/xz/Downloads/V2RayKernelInteractions.cpp	2022-09-21 23:59:59.811851509 +0800
@@ -132,10 +132,10 @@
         // reason...
         proc.setProcessChannelMode(QProcess::MergedChannels);
         proc.setProgram(corePath);
-        proc.setNativeArguments("--version");
+        proc.setNativeArguments("version");
         proc.start();
 #else
-        proc.start(corePath, { "--version" });
+        proc.start(corePath, { "version" });
 #endif
         proc.waitForStarted();
         proc.waitForFinished();
@@ -168,7 +168,7 @@
             QProcess process;
             process.setProcessEnvironment(env);
             DEBUG("Starting V2Ray core with test options");
-            process.start(kernelPath, { "-test", "-config", path }, QIODevice::ReadWrite | QIODevice::Text);
+            process.start(kernelPath, { "test", "--config", path }, QIODevice::ReadWrite | QIODevice::Text);
             process.waitForFinished();
 
             if (process.exitCode() != 0)
@@ -232,7 +232,7 @@
         env.insert("v2ray.location.asset", GlobalConfig.kernelConfig.AssetsPath());
         env.insert("XRAY_LOCATION_ASSET", GlobalConfig.kernelConfig.AssetsPath());
         vProcess->setProcessEnvironment(env);
-        vProcess->start(GlobalConfig.kernelConfig.KernelPath(), { "-config", filePath }, QIODevice::ReadWrite | QIODevice::Text);
+        vProcess->start(GlobalConfig.kernelConfig.KernelPath(), { "run", "--config", filePath }, QIODevice::ReadWrite | QIODevice::Text);
         vProcess->waitForStarted();
         kernelStarted = true;
 

```

**Comment by RungeCC** [comment]
I have an alternative [fork](https://github.com/RungeCC/Qv2ray/tree/v2ray5) fix this issue(and also compats to version4 api).

**Comment by RungeCC** [comment]
> `proc.start(corePath, { "version" });`

will break qv2ray when in version4 case(v2ray-core will try to start a session), so i think is not a good idea to do so.

**Comment by AliM1988** [comment]
@RungeCC 
Is there any v5 release for Windows?

**Pull request closed without merging**
