### PR TITLE
Dev ping refactor

### PR DESCRIPTION
**Pull request by DuckVador**
* new 3rdparty library libuv and uvw
* async ICMP ping (Windows implementation uses a thread pool)
* async TCP ping
* only one latency test thread
* stackless coroutine
* no longer install libuv files

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
@DuckVador Assigned reviewer @DuckSoft

**Comment by DuckSoft** [comment]
There are enormous changes. Questions to ask:
1. Linux packaging problem: can we use system libuv? 
   * if we can, what's the required version?
   * is there a switch in CMakeFiles?
2. Are these code tested?
3. Will this work for macOS?

**Comment by DuckVador** [comment]
> There are enormous changes. Questions to ask:
> 
>     1. Linux packaging problem: can we use system libuv?
>        
>        * if we can, what's the required version?
>        * is there a switch in CMakeFiles?
> 
>     2. Are these code tested?
> 
>     3. Will this work for macOS?

1. No switch CMakeFiles. The required version of libuv is v1.38 which is too high for most Linux distro.
2. I have tested on Windows and Linux.
3. ICMP ping status is unknown, TCP ping is a cross-platform implementation.

**Comment by DuckSoft** [comment]
@DuckVador assigned @qv2ray-dev: please have a test on macOS

**Comment by DuckVador** [comment]
Because of this [issue](https://github.com/skypjack/uvw/issues/212), macOS cannot normally destruct when exiting.

**Comment by DuckSoft** [comment]
Upstream has fixed this "n00b" bug. Let's update some submodule and have a test.

**Pull request merged**
