### PR TITLE
Fix tray text if minimized

### LINKED ISSUE #1296: 最小化后托盘菜单显示”隐藏“
- [*] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在首选项启用”登录时自动启动“，”自动连接“和”启动后最小化“后重新启动操作系统，在自动启动后打开托盘菜单显示“隐藏”而非“显示“，但此时主界面并未显示。点击”隐藏“后主界面显示，托盘菜单正确地显示为”隐藏“。  

## 如何触发这个 Bug：
1. 在首选项启用登录时”自动启动“，”自动连接“（我设置为了”记忆上次的连接“），”启动后最小化“
2. 重启操作系统
3. 鼠标右键点击 Qv2ray 托盘图标

### 相关截图或日志

<details>

```

[Init] High DPI scaling is enabled. 
[BaseApplication] Qv2ray 2.7.0-pre2 on Windows 10 Version 2009 x86_64 
[BaseApplication] Qv2ray Start Time:  52804266 
[BaseApplication] QV2RAY_BUILD_INFO Qv2ray built from Github Action 
[BaseApplication] QV2RAY_BUILD_EXTRA_INFO qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest 
[BaseApplication] QV2RAY_BUILD_NUMBER 6150 
[BaseApplication] This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
Copyright (c) 2019-2021 Qv2ray Development Group.
Third-party libraries that have been used in this program can be found in the About page. 
[PlatformApplication] Startup Options: parser.isSet(noAPIOption): 0 
[PlatformApplication] Startup Options: parser.isSet(debugLogOption): 0 
[PlatformApplication] Startup Options: parser.isSet(noAutoConnectionOption): 0 
[PlatformApplication] Startup Options: parser.isSet(noPluginsOption): 0 
[PlatformApplication] Command line: errorMessage:  
[PlatformApplication] Non-fatal error, continue starting up. 
[Translator] Found translations: en_US ja_JP yue zh_CN zh_TW 
[Translator] Found zh_CN in folder: C:/Users/user/scoop/apps/qv2ray-beta/current/lang 
[Translator] Successfully installed a translator for zh_CN 
[SettingsBackend] Application exec path: C:/Users/user/scoop/apps/qv2ray-beta/current 
[SettingsBackend] Found a config file, conf["config_version"].toString():  path: C:/Users/user/scoop/apps/qv2ray-beta/current/config/ 
[SettingsBackend] Path: C:/Users/user/scoop/apps/qv2ray-beta/current/config/  is valid. 
[SettingsBackend] Using  C:/Users/user/scoop/apps/qv2ray-beta/current/config/  as the config path. 
[Utils] Some comments have been removed from the json. 
[Translator] Found zh_CN in folder: C:/Users/user/scoop/apps/qv2ray-beta/current/lang 
[Translator] Removed translations 
[Translator] Successfully installed a translator for zh_CN 
[PluginHost] Reloading plugin list 
[PluginHost] Loading plugin: QvPlugin-BuiltinProtocolSupport.dll from: C:/Users/user/scoop/apps/qv2ray-beta/current/plugins 
[PluginHost] Loaded plugin: "Builtin Protocol Support" made by: "Qv2ray Core Workgroup" 
[PluginHost] Loading plugin: QvPlugin-BuiltinSubscriptionSupport.dll from: C:/Users/user/scoop/apps/qv2ray-beta/current/plugins 
[PluginHost] Loaded plugin: "Builtin Subscription Support" made by: "Qv2ray Core Workgroup" 
[PluginHost] Loading plugin: ssr.dll from: C:/Users/user/scoop/apps/qv2ray-beta/current/config/plugins 
[PluginHost] Loaded plugin: "SSR Plugin" made by: "Qv2ray Development Group" 
[Utils] Some comments have been removed from the json. 
[Utils] Some comments have been removed from the json. 
[PluginHost] qvplugin_ssr Initialize plugin. 
[Utils] Some comments have been removed from the json. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] ConnectionHandler Constructor. 
[Utils] Some comments have been removed from the json. 
[Utils] Some comments have been removed from the json. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: dwxlfxclabsu into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: uxbzicginuhd into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: ymxfqnwfifkf into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: fwtiezayvyhx into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: iqghgubonskq into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: lzwfdqcgzduz into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: frlllvcanevv into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: kchkvguvfrop into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: htjsbubbhqin into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: jolnfunffsmw into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: slnbskzcxyig into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: tswlconndkcz into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: fqwqqvmdbujj into cache. 
[Utils] Some comments have been removed from the json. 
[ConfigHandler] Loaded connection id: sfuqshnunjxi into cache. 
[gRPCBackend] API Worker initialised. 
[gRPCBackend] API Worker started. 
[StyleManager] Found factory style: windowsvista 
[StyleManager] Found factory style: Windows 
[StyleManager] Found factory style: Fusion 
[StyleManager] Found QSS style at: ":/uistyles/flatwhite.css" 
[StyleManager] Found QSS style at: ":/uistyles/psblack.css" 
[StyleManager] Applying UI style: Fusion 
[Utils] Some comments have been removed from the json. 
[RouteHandler] Processing a simple connection config 
[RouteHandler] Added global DNS config 
[InboundGenerator] Allocation is not used here, Not Implemented 
[InboundGenerator] Allocation is not used here, Not Implemented 
[RouteHandler] Added global inbound config 
[InboundGenerator] Allocation is not used here, Not Implemented 
[KernelHandler] Cannot disconnect when there's nothing connected. 
[KernelHandler] Creating kernel plugin instance for protocolshadowsocksr 
[KernelHandler] V2RayIntegration: 15000 = shadowsocksr 
[KernelHandler] Sending connection settings to kernel. 
[KernelHandler] Outbound protocol freedom is not a registered plugin outbound. 
[KernelHandler] Outbound protocol blackhole is not a registered plugin outbound. 
[KernelHandler] Applying new outbound settings. 
[KernelHandler] Starting kernels with V2RayIntegration. 
[KernelHandler] Starting kernel for protocol: shadowsocksr 
[V2RayInteraction] V2Ray output: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 windows/amd64);A unified platform for anti-censorship. 
[V2RayInteraction] V2Ray version: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 windows/amd64) 
[V2RayInteraction] Starting V2Ray core with test options 
[V2RayInteraction] Config file check passed. 
[V2RayInteraction] V2Ray kernel process status changed: Starting 
[V2RayInteraction] V2Ray kernel process status changed: Running 
[V2RayInteraction] Starting API 
[ConnectionItemWidget] ConnectionItemWidgetOnConnected signal received for: sfuqshnunjxi 
[MainWindowExtra] ProxyAddress: 127.0.0.1 
[SystemProxy] Setting up System Proxy 
[SystemProxy] Qv2ray will set system proxy to use HTTP 
[SystemProxy] Qv2ray will set system proxy to use SOCKS 
[SystemProxy] Windows proxy string: 127.0.0.1:8889 
[SystemProxy] System default proxy info: 
[SystemProxy] PROXY_TYPE_DIRECT 
[SystemProxy] 127.0.0.1:8889 
[SystemProxy] Setting system proxy for Global Proxy 
[SystemProxy] System default proxy info: 
[SystemProxy] PROXY_TYPE_DIRECT 
[SystemProxy] PROXY_TYPE_PROXY 
[SystemProxy] 127.0.0.1:8889 
[gRPCBackend] gRPC Version: 1.33.1

[GeositeReader] Reading geosites from: C:/Users/user/scoop/apps/xray/current/geosite.dat 
[GeositeReader] Loaded 856 geosite entries from data file. 
[GeositeReader] Reading geosites from: C:/Users/user/scoop/apps/xray/current/geoip.dat 
[GeositeReader] Loaded 251 geosite entries from data file.

[V2RayInteraction] V2Ray output: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 windows/amd64);A unified platform for anti-censorship.

[WidgetApplication] Client ID: 1 , message received, version: 6150 
[WidgetApplication] {"arguments":[0],"buildVersion":6150,"fullArgs":["C:\\Users\\user\\scoop\\apps\\qv2ray-beta\\2.7.0-pre2\\qv2ray.exe"],"version":"2.7.0-pre2"}
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows 10 19042.804

### 安装来源

- Scoop Qv2ray/mochi qv2ray-beta

#### SSR Plugin
版本: 3.0.0-pre3
安装来源: Scoop Qv2ray/mochi qv2ray-plugin-ssr-beta

### PR DESCRIPTION
**Pull request by dyhkwong**
Fix #1296

### CODE REVIEW

**Review by DuckSoft — APPROVED** [review]

**Review by U-v-U — APPROVED** [review]
I didn't perform a test, but it looks ok.

**Comment by U-v-U** [comment]
A better solution might be a `setState(bool)` function, I suggest. With rewriting some current implementations.

**Comment by DuckSoft** [comment]
Make it work. Make it right. Make it fast.

**Comment by DuckSoft** [comment]
I forgot to bump the BUILDVERSION. Sad.

**Pull request merged**
