### PR TITLE
[WIP] Multiplatform Darkmode Detection

### PR DESCRIPTION
**Pull request by DuckSoft**
tracker:
- [x] linux (@DuckSoft)
- [x] windows (@DuckSoft)
- [ ] macOS (**_someone else who is expert at macOS programming is needed_**)
- [ ] integration (@Qv2ray-dev)

### CODE REVIEW

**Comment by DuckSoft** [comment]
Cannot recognise a single word. I died. Need some help over there.
https://github.com/keepassxreboot/keepassxc/blob/6d2ca748787c71eab3adaf2071d5738ba7c28a52/src/gui/osutils/macutils/AppKitImpl.mm#L103-L109

**Comment by DuckSoft** [comment]
@Qv2ray-dev integration is ready to go, though macOS part of implementation is missing.
Have a look!

**Comment by Qv2ray-dev** [comment]
Not only the dark mode is required for macOS, the macOS-specifix `hide()` function is also required:

See: https://github.com/Qv2ray/Qv2ray/issues/370

**Comment by DuckSoft** [comment]
This is relevant to multiplatform, but irrelevant to darkmode detection.
Will impl in new branch.

**Pull request merged**
