### PR TITLE
Route editor redesign and refactor.

### PR DESCRIPTION
**Pull request by U-v-U**
WIP

### CODE REVIEW

**Comment by U-v-U** [comment]
Now ready for review.

**Comment by DuckSoft** [comment]
Are old routes safe to migrate?

**Comment by U-v-U** [comment]
@DuckSoft Tested using generated config.
Need even more testings.

The final config generation needs to be done before merging. (e.g. the chain expansion)

**Comment by U-v-U** [comment]
@DuckSoft Or we can merge and implement directly on the dev branch (to prevent future conflict)

**Comment by DuckSoft** [comment]
@U-v-U do not merge to dev yet, if things cannot migrate smoothly

**Comment by U-v-U** [comment]
@DuckSoft They could, just the new features are not supported yet, the Chain amd the ExternalReference

Rewrting the generarion engine could produce a large diff (and conflicts unfortunately).

Other components should work fine, by "fine" I mean there's no reason for them to break

**Comment by DuckSoft** [comment]
Testing In Progress

**Comment by U-v-U** [comment]
Chain generation and external connection id resolver has been implemented.

**Comment by U-v-U** [comment]
Testings of the compatibility with old complex connection config are currently ongoing.

**Pull request closed without merging**
